// Widget tag/category assignments
export const WIDGET_TAGS: Record<string, string[]> = {
  'clock':                ['Time'],
  'countdown':            ['Time'],
  'time-progress':        ['Time'],
  'holiday-calendar':     ['Time', 'Fun'],
  'f1-countdown':         ['Time', 'Sports'],
  'weather':              ['Environment'],
  'air-quality':          ['Environment'],
  'uv-index':             ['Environment'],
  'fire-hazard':          ['Environment'],
  'aurora-forecast':      ['Environment'],
  'drought-level':        ['Environment'],
  'groundwater-level':    ['Environment'],
  'satellite-view':       ['Environment'],
  'cafeteria-menu':       ['Campus'],
  'club-spotlight':       ['Campus'],
  'confessions':          ['Campus'],
  'group-fitness':        ['Campus', 'Sports'],
  'library-availability': ['Campus'],
  'job-board':            ['Campus'],
  'events-list':          ['Campus'],
  'climbing-gym':         ['Campus', 'Sports'],
  'bus-connection':       ['Transit'],
  'news-ticker':          ['Info'],
  'stock-quotes':         ['Info'],
  'exchange-rate':        ['Info'],
  'crypto-tracker':       ['Info'],
  'iss-tracker':          ['Info'],
  'rss-reader':           ['Info'],
  'horoscope':            ['Fun', 'Info'],
  'team-schedule':        ['Info', 'Sports'],
  'poster-carousel':      ['Media'],
  'poster-feed':          ['Media'],
  'slideshow':            ['Media'],
  'image':                ['Media'],
  'media-player':         ['Media'],
  'radio-station':        ['Media', 'Info'],
  'youtube':              ['Media'],
  'web':                  ['Media'],
  'rich-text':            ['Media'],
  'nothing-glyph':        ['Fun'],
  'bottle-spin':          ['Fun'],
  'rock-paper-scissors':  ['Fun'],
  'kaomoji':              ['Fun'],
  'coin-dice':            ['Fun'],
  'word-of-the-day':      ['Fun'],
  'flashcard':            ['Fun'],
  'audience-response':    ['Fun', 'Campus'],
  'qrcode':               ['Utility'],
  'widget-stack':         ['Utility'],
  'google-calendar':      ['Campus', 'Time'],
  'home-assistant':       ['Utility', 'Info'],
  'wifi-share':           ['Utility'],
  'calendar':             ['Campus', 'Time'],
  'google-sheets':        ['Media'],
  'canva':                ['Media'],
};

export function getWidgetTags(type: string): string[] {
  return WIDGET_TAGS[type] ?? ['Other'];
}

// All unique tags in display order
export const ALL_TAGS = ['Campus', 'Environment', 'Time', 'Info', 'Media', 'Transit', 'Sports', 'Fun', 'Utility'];
